[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["eutterba"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
bs4 = "^0.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
